Add more detailed debugging for PWS push

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,11 +4,11 @@ on:
   push:
     branches: [ main ]
     paths-ignore:
-      - '**.md'
+        - '**.md'
   pull_request:
     branches: [ main ]
     paths-ignore:
-      - '**.md'
+        - '**.md'
 
 jobs:
   build-and-push:
@@ -25,40 +25,24 @@ jobs:
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
-    - name: Debug Git Information
-      run: |
-        echo "Git status:"
-        git status
-        echo "Git remote -v:"
-        git remote -v
-        echo "Git branch:"
-        git branch -a
-        echo "Git log:"
-        git log --oneline --decorate --graph --all
-
-    - name: Push to PWS
+    - name: Check PWS remote, pull, merge, and push
       env:
         PWS_URL: ${{ secrets.PWS_URL }}
       run: |
-        # Check if main branch exists locally
-        if ! git show-ref --verify --quiet refs/heads/main; then
-          echo "Creating main branch"
-          git branch main
-        fi
+          # Check if master branch exists locally
+          if ! git show-ref --verify --quiet refs/heads/master; then
+            echo "Creating master branch"
+            git branch master
+          fi
+          
+          # Switch to master branch
+          git checkout master
 
-        # Switch to main branch
-        git checkout main
-
-        # Ensure that the local branch is up-to-date
-        git pull origin main
-
-        # Push to PWS and capture the output
-        echo "Pushing to PWS..."
-        push_output=$(git push $PWS_URL main:main 2>&1)
-        echo "$push_output"
-        if [[ $? -ne 0 ]]; then
-          echo "Push failed with output: $push_output"
-          echo "Error: Unable to push changes. Please check the error message above and resolve any conflicts manually."
-          exit 1
-        fi
-        echo "Push successful with output: $push_output"
+          # Push to master branch and capture the output
+          push_output=$(git push $PWS_URL main:master 2>&1)
+          if [[ $? -ne 0 ]]; then
+            echo "Push failed with output: $push_output"
+            echo "Error: Unable to push changes. Please check the error message above and resolve any conflicts manually."
+            exit 1
+          fi
+          echo "Push successful with output: $push_output"
